"""
Usage:
# Create train data:
python xml_to_csv.py -i [PATH_TO_IMAGES_FOLDER]/train -o [PATH_TO_ANNOTATIONS_FOLDER]/train_labels.csv
# Create test data:
python xml_to_csv.py -i [PATH_TO_IMAGES_FOLDER]/test -o [PATH_TO_ANNOTATIONS_FOLDER]/test_labels.csv
"""

import os
import glob
import pandas as pd
import argparse
import json
import xml.etree.ElementTree as ET


def xml_to_csv(path):
    """Iterates through all .xml files (generated by labelImg) in a given directory and combines them in a single Pandas datagrame.
    Parameters:
    ----------
    path : {str}
        The path containing the .xml files
    Returns
    -------
    Pandas DataFrame
        The produced dataframe
    """
    classes_names = []
    xml_list = []
    for json_file in glob.glob(path + "/*.json"):
<<<<<<< HEAD
        
        file_string = json_file.split('/')
        file_string = file_string[len(file_string)-1]+'.jpeg'
=======
        print(os.path.basename(json_file))
        file_string = json_file.split('/')
        file_string = file_string[len(file_string)-1]
        file_string = file_string.split('.')[0]
        file_string = file_string + '.jpeg'
>>>>>>> dd
        print(file_string)

        tree = open(json_file)
        root = json.load(tree)

        height = root["size"]["height"]
<<<<<<< HEAD
        width = root["size"]["width"]
=======
        width = root["size"]["width"] 
>>>>>>> dd

        for obj in root["objects"]:
            classes_names.append("classTitle")
            print(json_file.split('.')[0]+'.jpeg')
<<<<<<< HEAD
=======
            print(obj["points"]["exterior"][0][0] / width)
>>>>>>> dd
            value = (
                    file_string,
                    int(width),
                    int(height),
                    "Power_Cell",
<<<<<<< HEAD
                    int(obj["points"]["exterior"][0][0]),
                    int(obj["points"]["exterior"][1][0]),
                    int(obj["points"]["exterior"][0][1]),
                    int(obj["points"]["exterior"][1][1])
                    )
            xml_list.append(value)
=======
                    round(obj["points"]["exterior"][0][0] / width, 3),
                    round(obj["points"]["exterior"][0][1] / height, 3),
                    round(obj["points"]["exterior"][1][0] / width, 3),
                    round(obj["points"]["exterior"][1][1] / height, 3)
                    )
            xml_list.append(value)
        print(xml_list)
>>>>>>> dd
    column_name = [
        "filename",
        "width",
        "height",
        "class",
        "xmin",
        "ymin",
        "xmax",
        "ymax",
    ]
    xml_df = pd.DataFrame(xml_list, columns=column_name)
    classes_names = list(set(classes_names))
    classes_names.sort()
    return xml_df, classes_names


def main():
    # Initiate argument parser
    parser = argparse.ArgumentParser(
        description="Sample TensorFlow XML-to-CSV converter"
    )
    parser.add_argument(
        "-i",
        "--inputDir",
        help="Path to the folder where the input .xml files are stored",
        type=str,
    )
    parser.add_argument(
        "-o", "--outputFile", help="Name of output .csv file (including path)", type=str
    )

    parser.add_argument(
        "-l",
        "--labelMapDir",
        help="Directory path to save label_map.pbtxt file is specified.",
        type=str,
        default="",
    )

    args = parser.parse_args()

    if args.inputDir is None:
        args.inputDir = os.getcwd()
    if args.outputFile is None:
        args.outputFile = args.inputDir + "/labels.csv"

    assert os.path.isdir(args.inputDir)
    os.makedirs(os.path.dirname(args.outputFile), exist_ok=True)
    xml_df, classes_names = xml_to_csv(args.inputDir)
    xml_df.to_csv(args.outputFile, index=None)
    print("Successfully converted xml to csv.")
    if args.labelMapDir:
        os.makedirs(args.labelMapDir, exist_ok=True)
        label_map_path = os.path.join(args.labelMapDir, "label_map.pbtxt")
        print("Generate `{}`".format(label_map_path))

        # Create the `label_map.pbtxt` file
        pbtxt_content = ""
        for i, class_name in enumerate(classes_names):
            pbtxt_content = (
                pbtxt_content
                + "item {{\n    id: {0}\n    name: '{1}'\n}}\n\n".format(
                    i + 1, class_name
                )
            )
        pbtxt_content = pbtxt_content.strip()
        with open(label_map_path, "w") as f:
            f.write(pbtxt_content)


if __name__ == "__main__":
    main()
